services:
  backend:
    build: ./ferchat-api-rust/.
    ports:
      - "8000:8000"
    networks:
      - ferchat-net
  frontend:
    build: ./ferchat-web/.
    ports:
      - "5173:5173"
    networks:
      - ferchat-net
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=users
    build: ./ferchat-db
    volumes:
      - /home/fernando/dev/ferchat-full/ferchat-db/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ferchat-net

networks:
  ferchat-net:
    driver: bridge